# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_file',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.DateTimeField(default=1900, null=True),
        ),
    ]
