# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0004_song_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.CharField(default='', max_length=256),
        ),
    ]
