# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0010_auto_20161124_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='search_key',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
