"""empty message

Revision ID: 71d13ddf7631
Revises: 0ee3470eeb49
Create Date: 2018-02-06 21:17:29.634795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d13ddf7631'
down_revision = '0ee3470eeb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
