# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('image_file', models.CharField(max_length=256)),
                ('year', models.DateTimeField(default=1900)),
                ('rating', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
