# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0003_auto_20161106_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
