# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0005_song_track_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.IntegerField(null=True),
        ),
    ]
