# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0006_auto_20161124_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.IntegerField(null=True),
        ),
    ]
